---
- name: Set up all the other proxy stuff -- miscellaneous
  hosts: proxies_stg:proxies
  user: root
  gather_facts: true

  vars_files:
    - /srv/web/infra/ansible/vars/global.yml
    - "/srv/private/ansible/vars.yml"
    - /srv/web/infra/ansible/vars/{{ ansible_distribution }}.yml

  handlers:
  - import_tasks: "{{ handlers_path }}/restart_services.yml"

  tasks:
      # We retired this in favor of PDC
      # https://lists.fedoraproject.org/archives/list/rel-eng@lists.fedoraproject.org/thread/LOWVTF6WTS43LNPWDEISLXUELXAH5YXR/#LOWVTF6WTS43LNPWDEISLXUELXAH5YXR
    - ansible.builtin.file:
        dest=/etc/httpd/conf.d/apps.fedoraproject.org/fedora-releng-dash.conf
        state=absent
      tags: releng-dash
      notify: Reload proxyhttpd

  roles:

  - role: httpd/mime-type
    website: fedoraproject.org
    mimetype: image/vnd.microsoft.icon
    extensions:
    - .ico

  - role: httpd/fingerprints
    website: admin.fedoraproject.org

  - role: easyfix/proxy
    website: fedoraproject.org
    path: /easyfix

  - role: review-stats/proxy
    website: fedoraproject.org
    path: /PackageReviewStatus

  - role: apps-fp-o
    website: apps.fedoraproject.org
    path: /

  - role: pkgdb-proxy
    tags:
    - pkgdb2

  - role: security.txt
    tags:
    - security.txt
